// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CommandRequest = {
    id: number;
    method: string;
    params: {
        [key: string]: unknown;
    };
    [key: string]: unknown | number | string;
};

export type DemoCreate = {
    title: string;
    description?: (string | null);
};

export type DemoPublic = {
    id: string;
    title: string;
    description?: (string | null);
    owner_id: string;
    created_at: string;
};

export type DemosPublic = {
    data: Array<DemoPublic>;
    count: number;
};

export type DemoUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Generic API message response.
 */
export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type StreamRequest = {
    channels: Array<(string)>;
    namespaces?: (Array<Array<(string)>> | null);
    depth?: (number | null);
    since?: (number | null);
    [key: string]: unknown | string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    password: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
};

export type UserPublic = {
    id: string;
    email: string;
    is_active: boolean;
    is_superuser: boolean;
    full_name?: (string | null);
    created_at: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ChatCommandData = {
    requestBody: CommandRequest;
    threadId: string;
};

export type ChatCommandResponse = ({
    [key: string]: unknown;
});

export type ChatStreamEventsData = {
    requestBody: StreamRequest;
    threadId: string;
};

export type ChatStreamEventsResponse = (unknown);

export type ChatThreadStateData = {
    threadId: string;
};

export type ChatThreadStateResponse = ({
    [key: string]: unknown;
});

export type ChatCancelRunData = {
    action?: string;
    runId: string;
    threadId: string;
    wait?: number;
};

export type ChatCancelRunResponse = (void);

export type DemosReadDemosData = {
    limit?: number;
    skip?: number;
};

export type DemosReadDemosResponse = (DemosPublic);

export type DemosCreateDemoData = {
    requestBody: DemoCreate;
};

export type DemosCreateDemoResponse = (DemoPublic);

export type DemosReadDemoData = {
    demoId: string;
};

export type DemosReadDemoResponse = (DemoPublic);

export type DemosUpdateDemoData = {
    demoId: string;
    requestBody: DemoUpdate;
};

export type DemosUpdateDemoResponse = (DemoPublic);

export type DemosDeleteDemoData = {
    demoId: string;
};

export type DemosDeleteDemoResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SystemTestEmailData = {
    emailTo: string;
};

export type SystemTestEmailResponse = (Message);

export type SystemHealthLiveResponse = (boolean);

export type SystemHealthReadyResponse = (boolean);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);