from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import Protocol, TypeAlias

MessageHandler: TypeAlias = Callable[[str], Awaitable[None]]


class ResumeBackend(Protocol):
    async def ensure_ready(self) -> None: ...

    async def claim_active(self, key: str, *, ttl_seconds: int) -> bool: ...

    async def get(self, key: str) -> str | None: ...

    async def set(self, key: str, value: str, *, ttl_seconds: int) -> None: ...

    async def expire(self, key: str, *, ttl_seconds: int) -> None: ...

    async def publish(self, channel: str, message: str) -> int: ...

    async def subscribe(self, channel: str, handler: MessageHandler) -> None: ...

    async def unsubscribe(self, channel: str) -> None: ...

    async def close(self) -> None: ...
